<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle()->setSeparator(' - ')->setAutoEscape(false);
$this->headTitle('Pin Your Pizza!');
$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
$this->headMeta()->appendName(
    'viewport', 'width=device-width, initial-scale=1'
);
$this->headLink(
    array(
        'rel' => 'shortcut icon',
        'href' => '/assets/custom/img/favicon.ico'
    )
);
$this->headLink()->prependStylesheet(
    '/assets/vendor/bootstrap-3.3.5/css/bootstrap.min.css'
);
$this->headLink()->prependStylesheet(
    '/assets/vendor/font-awesome-4.4.0/css/font-awesome.min.css'
);
$this->headLink()->appendStylesheet(
    '/assets/vendor/raty-2.7.0/jquery.raty.css'
);
$this->headLink()->appendStylesheet('/assets/custom/css/styles.css');

$this->inlineScript()->prependFile(
    '/assets/vendor/raty-2.7.0/jquery.raty.js'
);
$this->inlineScript()->prependFile(
    '/assets/vendor/bootstrap-3.3.5/js/bootstrap.min.js', 'text/javascript'
);
$this->inlineScript()->prependFile(
    '/assets/vendor/jquery-2.1.4/jquery-2.1.4.min.js', 'text/javascript'
);
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <?= $this->headTitle() . "\n"; ?>
  <?= $this->headMeta() . "\n"; ?>
  <?= $this->headLink() . "\n"; ?>
  <?= $this->headScript() . "\n"; ?>
  <?= $this->headStyle() . "\n"; ?>
</head>
<body>
<?= $this->header ?>
<div>
  <main class="container">
    <?= $this->content ?>
  </main>
</div>
<?= $this->footer ?>
<?= $this->inlineScript(); ?>
</body>
</html>
