<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<div class="container">
  <header>
    <div class="row">
      <div class="col-xs-12">
        <a href="<?= $this->url('home'); ?>">
          <img src="/assets/custom/img/logo.png" class="logo">
        </a>
      </div>
    </div>
  </header>
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">
          <?= $this->translate('application_action_toggle_navigation'); ?>
        </span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <a href="/">
            <i class="fa fa-home"></i>
            <?= $this->translate('application_navigation_home'); ?>
          </a>
        </li>
        <li>
          <a href="<?= $this->url('pizza-pinboard') ?>">
            <i class="fa fa-thumbs-up"></i>
            <?= $this->translate('pizza_navigation_pinboard'); ?>
          </a>
        </li>
        <?php if ($this->userAllowed('user-intro')): ?>
          <li>
            <a href="<?= $this->url('user-intro') ?>">
              <i class="fa fa-user"></i>
              <?= $this->translate('user_navigation_intro'); ?>
            </a>
          </li>
        <?php else: ?>
          <li>
            <a href="<?= $this->url('user-handle-logout') ?>">
              <i class="fa fa-user"></i>
              <?= $this->translate('user_navigation_logout'); ?>
              (<?= $this->userIdentity()->first_name ?>
              <?= $this->userIdentity()->last_name ?>)
            </a>
          </li>
        <?php endif; ?>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="<?= $this->url(null, ['lang' => 'de']) ?>">
            <?= $this->translate('application_navigation_german'); ?>
          </a>
        </li>
        <li>
          <a href="<?= $this->url(null, ['lang' => 'en']) ?>">
            <?= $this->translate('application_navigation_english'); ?>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</div>
