<?php
/**
 * ZF3 book Vote my Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<h1><?php echo $this->pizza['name']; ?></h1>
<div class="row">
    <?php
    $this->inlineScript()->appendScript(
        "
    $('#stars-" . $this->pizza['id'] . "').raty({
        readOnly: true,
        score   : " . $this->pizza['rate'] . ",
        half    : true,
        starOff : '/assets/vendor/raty-2.7.0/images/star-off.png',
        starOn  : '/assets/vendor/raty-2.7.0/images/star-on.png',
        starHalf: '/assets/vendor/raty-2.7.0/images/star-on.png'
    });
    "
    ); ?>
    <div class="col-md-6">
        <div class="thumbnail text-center">
            <img src="<?php echo $this->pizza['image'] ?>"
                 title="<?php echo $this->pizza['name'] ?>">

            <div class="caption">
                <p id="stars-<?php echo $this->pizza['id'] ?>"></p>
                <p class="small">
                    <?php echo $this->pizza['name'] ?>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="well">
            <?php foreach ($this->pizza['comments'] as $comment) : ?>
                <?php echo $comment; ?>
                <hr>
            <?php endforeach ?>
        </div>
    </div>
</div>