<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php $this->headTitle('404 Not Found'); ?>

<h1>Oops!</h1>
<h2>This is awkward.</h2>
<p>We encountered a 404 Not Found error.</p>
<p>
    You are looking for something that doesn't exist or may have moved. Check out one of the links on this page
    or head back to <a href="<?php echo $this->url('home') ?>">Home</a>.
</p>
