<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php $this->headTitle(sprintf('%d %s', $this->status, $this->reason)); ?>

<h1><?php echo $this->translate('application_heading_oops'); ?></h1>
<h2><?php echo $this->translate('application_heading_awkward'); ?></h2>

<p>
    <?php echo sprintf(
        $this->translate('application_message_not_found_500'),
        $this->escapeHtml(sprintf('%d %s', $this->status, $this->reason))
    ); ?>
</p>

<?php if ($this->status == 404) : ?>
    <p>
        <?php echo sprintf(
            $this->translate('application_message_not_found_404'),
            $this->url('home')
        ); ?>
    </p>
<?php else : ?>
    <pre><code><?php var_dump($this->error); ?></code></pre>
<?php endif; ?>
