<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

if ($this->status == 404) {
    $title     = 'Seite nicht gefunden';
    $header    = '404 - Seite wurde nicht gefunden';
    $subHeader = 'Das ist uns echt unangenehm';
    $message   = 'Die angeforderte Seite wurde nicht gefunden. Du suchst etwas, das hier nicht existiert oder verschoben wurde.';
} else {
    $title     = 'Fehler aufgetreten';
    $header    = $this->status . ' - Es ist ein Fehler aufgetreten';
    $subHeader = 'Das ist uns echt unangenehm';
    $message   = 'Wir sind auf einen "%1$s" Fehler gestossen.';
}

$this->headTitle($title);
?>
<h1><?= $header ?></h1>
<div class="alert alert-danger">
  <h3><?= $subHeader; ?></h3>
  <p><?= $message; ?></p>
  <hr>
  <p class="text-center">
    <a class="btn btn-success" href="<?= $this->url('home'); ?>">
      Zurück zur Startseite
    </a>
  </p>
</div>
