<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<h1><?= $this->welcome; ?></h1>
<div class="well text-center">
  <h3>
    <i class="fa fa-hourglass fa-spin"></i>
    &nbsp; In Kürze mehr... &nbsp;
    <i class="fa fa-hourglass fa-spin"></i>
  </h3>
</div>
