<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle()->setSeparator(' - ')->setAutoEscape(false);
$this->headTitle('Pin Your Pizza!');
$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
$this->headMeta()->appendName(
    'viewport', 'width=device-width, initial-scale=1'
);
$this->headLink(
    array(
        'rel' => 'shortcut icon',
        'href' => '/assets/custom/img/favicon.ico'
    )
);
$this->headLink()->prependStylesheet(
    '/assets/vendor/bootstrap-3.3.5/css/bootstrap.min.css'
);
$this->headLink()->prependStylesheet(
    '/assets/vendor/font-awesome-4.4.0/css/font-awesome.min.css'
);
$this->headLink()->appendStylesheet(
    '/assets/vendor/raty-2.7.0/jquery.raty.css'
);
$this->headLink()->appendStylesheet('/assets/custom/css/styles.css');

$this->inlineScript()->prependFile(
    '/assets/vendor/raty-2.7.0/jquery.raty.js'
);
$this->inlineScript()->prependFile(
    '/assets/vendor/bootstrap-3.3.5/js/bootstrap.min.js', 'text/javascript'
);
$this->inlineScript()->prependFile(
    '/assets/vendor/jquery-2.1.4/jquery-2.1.4.min.js', 'text/javascript'
);
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <?php echo $this->headTitle() . "\n"; ?>
    <?php echo $this->headMeta() . "\n"; ?>
    <?php echo $this->headLink() . "\n"; ?>
    <?php echo $this->headScript() . "\n"; ?>
    <?php echo $this->headStyle() . "\n"; ?>
</head>
<body>
<div class="container">
    <header>
        <div class="row">
            <div class="col-xs-12">
                <a href="<?php echo $this->url('home'); ?>">
                    <img src="/assets/custom/img/logo.png" class="logo">
                </a>
            </div>
        </div>
    </header>
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">
                    Toggle navigation
                </span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/">
                        <i class="fa fa-home"></i> Home
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('pizza-intro') ?>">
                        <i class="fa fa-thumbs-up"></i> Pizza Intro
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>

<div>
    <main class="container">
        <?php echo $this->content ?>
    </main>
</div>

<footer id="footer">
    <div class="footer-top"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <h4>ZF3buch Pin Your Pizza!</h4>
                <p>
                    Dieses Demoprojekt wurde mit dem
                    <a href="https://github.com/zendframework/zend-expressive-skeleton/"
                       target="_blank">
                        Zend\Expressive Skeleton
                    </a> erstellt und
                    dann angepasst. Dieses Übungsprojekt ist für Sie
                    gedacht, um das Gelernte weiter vertiefen zu können.
                </p>
            </div>
            <div class="col-lg-4">
                <h4>Zend Framework Links</h4>
                <ul>
                    <li>
                        <a href="http://framework.zend.com/"
                           target="_blank">
                            Zend Framework Website </a>
                    </li>
                    <li>
                        <a href="http://modules.zendframework.com/"
                           target="_blank">
                            Zend Framework 3 Module </a>
                    </li>
                    <li>
                        <a href="https://github.com/zendframework/"
                           target="_blank">
                            Zend Framework Github </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-4">
                <h4>ZF3buch Links</h4>
                <ul>
                    <li>
                        <a href="http://www.zendframeworkbuch.de/"
                           target="_blank">
                            Website zum ZF3 Buch </a>
                    </li>
                    <li>
                        <a href="https://github.com/zf3buch/pin-your-pizza"
                           target="_blank">
                            GitHub Repository ZF3buch Pin Your Pizza!</a>
                    </li>
                    <li>
                        <a href="http://www.ralfeggert.de" target="_blank">
                            Homepage Ralf Eggert </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<?php echo $this->inlineScript(); ?>
</body>
</html>
