<?php
/**
 * ZF3 book Pin Your Pizza Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/pin-your-pizza
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use Pizza\Form\CommentForm;

$urlVote    = $this->url('pizza-vote', ['id' => $this->pizza['id']]);
$urlComment = $this->url('pizza-comment', ['id' => $this->pizza['id']]);

/** @var CommentForm $form */
$form = $this->commentForm;
$form->setAttribute('action', $urlComment);

?>
<h1><?php echo $this->pizza['name']; ?></h1>
<div class="row">
    <?php
    $this->inlineScript()->appendScript(
        "
    $('#stars-" . $this->pizza['id'] . "').raty({
        score   : " . $this->pizza['rate'] . ",
        half    : true,
        starOff : '/assets/vendor/raty-2.7.0/images/star-off.png',
        starOn  : '/assets/vendor/raty-2.7.0/images/star-on.png',
        starHalf: '/assets/vendor/raty-2.7.0/images/star-on.png',
        click: function(score, evt) {
            $(location).attr('href','" . $urlVote . "?star=' + (Math.floor(score) + 1));
        }
    });
    "
    ); ?>
    <div class="col-md-6">
        <div class="thumbnail text-center">
            <img src="<?php echo $this->pizza['image'] ?>"
                 title="<?php echo $this->pizza['name'] ?>">

            <div class="caption">
                <p id="stars-<?php echo $this->pizza['id'] ?>"></p>

                <p>
                    <?php echo $this->pizza['name'] ?>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <?php foreach ($this->pizza['comments'] as $comment) : ?>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <?php
                    echo sprintf(
                        $this->translate('pizza_message_comment'),
                        $comment['name'],
                        $this->dateFormat(
                            strtotime($comment['date']),
                            IntlDateFormatter::LONG,
                            IntlDateFormatter::NONE
                        ),
                        $this->dateFormat(
                            strtotime($comment['date']),
                            IntlDateFormatter::NONE,
                            IntlDateFormatter::LONG
                        )
                    );
                    ?>
                </div>
                <div class="panel-body">
                    <?php echo $comment['text']; ?>
                    <?php if ($this->userAllowed(
                        'pizza-delete-comment'
                    )
                    ): ?>
                        <?php
                        $urlDelete = $this->url(
                            'pizza-delete-comment',
                            [
                                'id'        => $this->pizza['id'],
                                'commentId' => $comment['id'],
                            ]
                        );
                        ?>
                        <p>
                            <a href="<?php echo $urlDelete; ?>"
                               class="btn btn-danger">
                                <?php echo $this->translate(
                                    'pizza_action_delete_comment'
                                ); ?>
                            </a>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach ?>
        <?php if ($this->userAllowed('pizza-comment')): ?>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <?php
                    echo sprintf(
                        $this->translate('pizza_heading_new_comment'),
                        $this->pizza['name']
                    );
                    ?>
                </div>
                <div class="panel-body">
                    <?php echo $this->bootstrapForm($form); ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<div class="row">
    <p class="text-center">
        <a href="<?php echo $this->url('home') ?>"
           class="btn btn-success">
            <?php echo $this->translate('pizza_action_back_pinboard'); ?>
        </a>
    </p>
</div>